name: App

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: CXX=g++-9 cmake -Happ -Bbuild

    - name: build
      run: CXX=g++-9 cmake --build build -j4

    - name: run
      run: ./build/SortnetApp --info
